org: upstandfm
app: api
service: account

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  cfnRole: ${secrets:CFN_ROLE_ARN}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: upstandfm-deployments
    serverSideEncryption: AES256
  environment:
    # Reuse TCP connection to reduce request latency
    # For more info see:
    # https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24630
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AUTH0_DOMAIN: ${secrets:AUTH0_DOMAIN}
    AUTH0_ACCOUNT_CLIENT_ID: ${secrets:AUTH0_ACCOUNT_CLIENT_ID}
    AUTH0_ACCOUNT_CLIENT_SECRET: ${secrets:AUTH0_ACCOUNT_CLIENT_SECRET}
    AUTH0_APP_CLIENT_ID: ${secrets:AUTH0_APP_CLIENT_ID}

package:
  exclude:
    - ./*
    - ./**/*.spec.js
  include:
    - node_modules
    - src

functions:
  inviteUser:
    handler: src/handlers.inviteUser
    description: SNS topic subscriber that invites a single user
    events:
      - sns: ${state:infra.newInviteTopicArn}
