org: upstandfm
app: api
service: invite-users

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  cfnRole: ${secrets:CFN_ROLE_ARN}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: upstandfm-deployments
    serverSideEncryption: AES256
  environment:
    # Reuse TCP connection to reduce request latency
    # For more info see:
    # https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24630
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  exclude:
    - ./*
    - ./**/*.spec.js
  include:
    - node_modules
    - src

functions:
